version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - PORT=5000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_ORIGIN=http://localhost:3000
      - GEMINI_IMAGE_MODEL=gemini-2.5-flash-preview
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
